export interface LenderCriteria {
  minimumAcademicScore: string;
  admissionRequirement: string;
  eligibleCourses: string[];
  recognizedUniversities: string[];
  coApplicantRequired: boolean;
  creditScoreRequirement: string;
  collateralRequired: boolean;
  collateralDetails: {
    threshold?: string;
    acceptedTypes: string[];
  };
  incomeProofRequired: string[];
  moratoriumPeriod: string;
  processingTime: string;
  interestRates: string;
  prepaymentCharges: string;
  loanLimits: {
    withoutCollateral?: string;
    withCollateral?: string;
  };
  easeOfApproval: string;
}

export interface Lender {
  id?: string; // Auto-generated by Firestore
  name: string;
  logoUrl?: string;
  description?: string;
  countries: string[];
  criteria: LenderCriteria;
  website?: string;
  contactEmail?: string;
  contactPhone?: string;
  isActive: boolean;
  interestRate?: number;
  maxLoanAmount?: number;
  minCreditScore?: number;
  createdAt?: Date;
  updatedAt?: Date;
  // Allow additional dynamic fields
  [key: string]: any;
}

export interface LenderFormData extends Omit<Lender, 'id' | 'createdAt' | 'updatedAt'> {
  id?: string;
}

export interface LenderUploadResult {
  success: number;
  failed: number;
  errors?: Array<{ row: number; error: string }>;
}

export const DEFAULT_LENDER: Omit<Lender, 'name' | 'countries' | 'criteria'> = {
  logoUrl: '',
  description: '',
  website: '',
  contactEmail: '',
  contactPhone: '',
  isActive: true,
};
