export interface LenderCriteria {
  minimumAcademicScore: string;
  admissionRequirement: string;
  eligibleCourses: string[];
  recognizedUniversities: string[];
  coApplicantRequired: boolean;
  creditScoreRequirement: string;
  collateralRequired: boolean;
  collateralDetails: {
    threshold?: string;
    acceptedTypes: string[];
  };
  incomeProofRequired: string[];
  moratoriumPeriod: string;
  processingTime: string;
  interestRates: string;
  prepaymentCharges: string;
  loanLimits: {
    withoutCollateral?: string;
    withCollateral?: string;
  };
  easeOfApproval: string;
}

export interface Lender {
  id?: string; // Auto-generated by Firestore
  name: string;
  /** List of universities this lender will fund, or 'ALL' for all universities */
  fundedUniversities?: string[] | 'ALL';
  /** List of courses this lender will fund, or 'ALL' for all courses */
  fundedCourses?: string[] | 'ALL';
  /** Type of loan (secured/unsecured/education etc) */
  loanType?: string;
  /** Co-Signer status (required/optional/none) */
  coSignerStatus?: string;
  /** Rate of Interest (additional field for matching) */
  rateOfInterest?: string;
  /** Currency of the loan */
  loanCurrency?: string;
  /** Tuition fees covered (Yes/No/Partial) */
  tuitionFeesCovered?: string;
  /** Self contribution or deposit funding (Yes/No/Partial) */
  selfContributionFunding?: string;
  /** Living expenses covered (Yes/No/Partial) */
  livingExpensesCovered?: string;
  /** TAT for Sanction Letter */
  tatForSanctionLetter?: string;
  logoUrl?: string;
  description?: string;
  lenderType?: string;
  baseCountry?: string;
  targetNationalities?: string[]; // Alias for countries
  countries: string[];
  bankType?: string;
  maxLoanAmountIndia?: string;
  maxLoanAmountAbroad?: string;
  loanBrandName?: string;
  website?: string;
  contactEmail?: string;
  contactPhone?: string;
  isActive: boolean;
  interestRate?: number;
  maxLoanAmount?: number;
  minCreditScore?: number;
  createdAt?: Date;
  updatedAt?: Date;
  criteria: LenderCriteria;
  // Allow additional dynamic fields
  [key: string]: any;
}

export interface LenderCriteria {
  minimumAcademicScore: string;
  admissionRequirement: string;
  eligibleCourses: string[];
  recognizedUniversities: string[];
  coApplicantRequired: boolean;
  creditScoreRequirement: string;
  collateralRequired: boolean;
  collateralDetails: {
    threshold?: string;
    acceptedTypes: string[];
  };
  incomeProofRequired: string[];
  moratoriumPeriod: string;
  processingTime: string;
  interestRates: string;
  prepaymentCharges: string;
  loanLimits: {
    withoutCollateral?: string;
    withCollateral?: string;
  };
  easeOfApproval: string;
}


export interface LenderFormData extends Omit<Lender, 'id' | 'createdAt' | 'updatedAt'> {
  id?: string;
}

export interface LenderUploadResult {
  success: number;
  failed: number;
  errors?: Array<{ row: number; error: string }>;
}

export const DEFAULT_LENDER: Omit<Lender, 'name' | 'countries' | 'criteria'> = {
  logoUrl: '',
  description: '',
  website: '',
  contactEmail: '',
  contactPhone: '',
  isActive: true,
};
