import { Loader2, LogOut, Dashboard, User, Settings, FileText, Users, Building2, CreditCard, HelpCircle, ChevronDown, ChevronRight, Check, X, Plus, Trash2, Edit, MoreHorizontal, Search, Filter, ChevronLeft, ChevronUp, ArrowUpDown, Eye, Download, Upload, Calendar, Clock, AlertCircle, CheckCircle, XCircle, Info, ExternalLink, Menu, Moon, Sun, type Icon as LucideIcon } from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  logout: LogOut,
  dashboard: Dashboard,
  user: User,
  settings: Settings,
  file: FileText,
  users: Users,
  building: Building2,
  creditCard: CreditCard,
  help: HelpCircle,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  check: Check,
  x: X,
  plus: Plus,
  trash: Trash2,
  edit: Edit,
  more: MoreHorizontal,
  search: Search,
  filter: Filter,
  eye: Eye,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  clock: Clock,
  alert: AlertCircle,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  info: Info,
  external: ExternalLink,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  arrowUpDown: ArrowUpDown,
};

export type IconName = keyof typeof Icons;
